version: '3'
services:
  juno:
    container_name: juno
    image: fee-abstraction:juno
    volumes:
      - ./config/juno:/home/juno/.juno
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
  osmosis:
    container_name: osmosis
    image: fee-abstraction:osmosis
    volumes:
      - ./config/osmosis:/home/osmosis/.osmosisd
    ports:
      - "26357:26657"
      - "1287:1317"
      - "9060:9090"
  relayer:
    container_name: relayer
    image: fee-abstraction:relayer
    volumes:
      - ./config/relayer-config:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "juno-osmosis" ]
