version: '3'
services:
  # juno:
  #   container_name: juno
  #   image: fee-abstraction:juno
  #   volumes:
  #     - ./config/juno:/home/juno/.juno
  #   ports:
  #     - "26657:26657"
  #     - "1317:1317"
  #     - "9090:9090"
  fachain:
    container_name: fachain
    image: fee-abstraction:fachain
    volumes:
      - ./config/fachain:/home/fachain/.fachain
    ports:
      - "26457:26657"
      - "1217:1317"
      - "9080:9090"
  osmosis:
    container_name: osmosis
    image: fee-abstraction:osmosis
    volumes:
      - ./config/osmosis:/home/osmosis/.osmosisd
    ports:
      - "26357:26657"
      - "1117:1317"
      - "9060:9090"
  relayer:
    container_name: relayer
    image: fee-abstraction:relayer
    volumes:
      - ./config/relayer-config:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "fachain-osmosis" ]
  # sc-relayer:
  #   container_name: sc-relayer
  #   image: fee-abstraction:relayer
  #   volumes:
  #     - ./config/relayer-sc-config:/home/relayer/.relayer
  #   restart: always
  #   command: [ "bash", "start.sh", "sc_juno-osmosis" ]
